# Generated by Django 3.1.3 on 2020-11-16 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='massage_date',
            new_name='message_date',
        ),
    ]
